title = "Distributed EDA config"

[dist]
	master-url = "localhost"
	port-a = "5557"
	port-b = "5558"

#[algorithm]
#	method = "eda"

[eda]
	generations = 1000
	population = 1000
	tournament = 2
	output-probabilities = "./output-probabilities-eda"

[rules]
	input = "/home/jgcarvalho/gocode/src/github.com/jgcarvalho/zeca-create-rule/rose_special.rule"
	# input = "/home/jgcarvalho/teste/zeca-search/test_g20.rule"
	output = "./output-rules"

[db]
	# db-dir = "/home/jgcarvalho/sync/data/multissdb/"
	db-dir = "/home/jgcarvalho/sync/data/multissdb/tmp/"
	# db-name = "chameleonic.db"
	db-name = "teste.db"
	bucket-name = "proteins"
	init = "SeqHPRoseSpecial"
	target = "All3HPRoseSpecial"

[ca]
	steps = 1000
	ignore-steps = 100
